steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_IMAGE_TAG}-${SHORT_SHA}', './$REPO_NAME/docker' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:${_IMAGE_TAG}-${SHORT_SHA}"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["tag", "gcr.io/$PROJECT_ID/$REPO_NAME:${_IMAGE_TAG}-${SHORT_SHA}", "gcr.io/$PROJECT_ID/$REPO_NAME:${_IMAGE_TAG}"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:${_IMAGE_TAG}"]
timeout: 1800s
options:
  machineType: 'UNSPECIFIED'
