steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_REPO_NAME}:${_IMAGE_TAG}', './test' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_REPO_NAME}:${_IMAGE_TAG}"]
timeout: 1800s
options:
  machineType: 'UNSPECIFIED'